name: Build Driftwood Kernel for Picasso

on: 
  schedule:
    - cron:  '0 22 * * 1,5'
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: 
      - '.github/workflows/picasso.yml'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kernel Source Code
      uses: actions/checkout@v3
      with:
        github-server-url: 'https://github.com'
        repository: EndCredits/kernel_xiaomi_sm7250
        ref: android-4.19-main
        path: android-kernel
      
    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install git-core git-lfs gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
    
    - name: Download Clang Toolchain
      run: |
        git lfs clone -b amd64-kernel-arm --depth 1 https://codeberg.org/Mandi-Sa/clang.git  clang
        cd clang
        chmod -R +x ./
        CLANG_DIR=`pwd`
        echo "CLANG_DIR=$CLANG_DIR" >> $GITHUB_ENV
      
    - name: Setup KernelSU
      run: |
        cd android-kernel
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        
    - name: Build Kernel
      run: |
        PATH=${{ env.CLANG_DIR }}/bin:$PATH
        clang -v
        cd android-kernel
        bash ./build.sh all
        cd ../out/AnyKernel3-picasso/
        FINAL_ZINAME=`ls Driftwood*.zip`
        echo "FINAL_ZINAME=$FINAL_ZINAME" >> $GITHUB_ENV

    - name: Upload Kernel Image ZIP
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.FINAL_ZINAME }}
        path: out/AnyKernel3-picasso/Driftwood*
        

    
          

